### ISSUE TITLE
BOT ISSUES

### ISSUE THREAD

**Issue by twistzer0** [mouricedevs/Gifted-Md#43]
Please is happening to the bot I can't deploy anymore

**Comment by Bl-toxic** [comment]
Same here I can't deploy and it shows me dis image 
![Screenshot_20240513-171128](https://github.com/mouricedevs/Gifted-Md/assets/169436701/9d817c63-5152-4bef-b19d-8ecd6ef65111)

**Comment by mouricedevs** [comment]
Deployment is available now
