### ISSUE TITLE
Bot Not working 

### ISSUE THREAD

**Issue by BKIRUXHKIRUXH** [mouricedevs/Gifted-Md#53]
I deployed the bot but it's not working

**Comment by Ste-ph-en** [comment]
My bot as well it's not working

**Comment by mouricedevs** [comment]
Deploy without editing repo and it won't fail

**Comment by V1tali5** [comment]
Bot not deploying

**Comment by V1tali5** [comment]
Credit card issue

**Comment by V1tali5** [comment]
Credit card issue
