### ISSUE TITLE
Technical error 

### ISSUE THREAD

**Issue by Hulkman123** [mouricedevs/Gifted-Md#57]
![IMG-20240511-WA0043](https://github.com/mouricedevs/Gifted-Md/assets/171244888/eb0ce289-da7a-4eff-abd1-2bf511ff8989)
![Screenshot_2024-05-31-11-39-32-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/mouricedevs/Gifted-Md/assets/171244888/4aac23cc-79ae-4a05-af0c-0a68bcf9fc8d)

**Comment by mouricedevs** [comment]
Sync your forked repo to automatically have the new session links
